In [2]:
from transformers import PreTrainedModel, AutoModel, AutoModelForCausalLM
import torch.nn.functional as F

from transformers.models.qwen3.modeling_qwen3 import Qwen3Model



/nfs/roberts/project/pi_zy286/bml62/hyperbolic_rag/vllm_rag_env/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [3]:
model = AutoModel.from_pretrained("Qwen/Qwen3-1.7B")
model2 = AutoModelForCausalLM.from_pretrained("Qwen/Qwen3-1.7B")

Loading weights: 100%|██████████| 310/310 [00:00<00:00, 55475.48it/s]
Qwen3Model LOAD REPORT from: Qwen/Qwen3-1.7B
Key            | Status     |  | 
---------------+------------+--+-
lm_head.weight | UNEXPECTED |  | 

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
Loading weights: 100%|██████████| 311/311 [00:00<00:00, 53016.93it/s]


In [4]:
print(model)

Qwen3Model(
  (embed_tokens): Embedding(151936, 2048)
  (layers): ModuleList(
    (0-27): 28 x Qwen3DecoderLayer(
      (self_attn): Qwen3Attention(
        (q_proj): Linear(in_features=2048, out_features=2048, bias=False)
        (k_proj): Linear(in_features=2048, out_features=1024, bias=False)
        (v_proj): Linear(in_features=2048, out_features=1024, bias=False)
        (o_proj): Linear(in_features=2048, out_features=2048, bias=False)
        (q_norm): Qwen3RMSNorm((128,), eps=1e-06)
        (k_norm): Qwen3RMSNorm((128,), eps=1e-06)
      )
      (mlp): Qwen3MLP(
        (gate_proj): Linear(in_features=2048, out_features=6144, bias=False)
        (up_proj): Linear(in_features=2048, out_features=6144, bias=False)
        (down_proj): Linear(in_features=6144, out_features=2048, bias=False)
        (act_fn): SiLUActivation()
      )
      (input_layernorm): Qwen3RMSNorm((2048,), eps=1e-06)
      (post_attention_layernorm): Qwen3RMSNorm((2048,), eps=1e-06)
    )
  )
  (norm): Qwen3RM

In [6]:
print(model2.lm_head)

Linear(in_features=2048, out_features=151936, bias=False)


In [5]:
print(Qwen3Model)

<class 'transformers.models.qwen3.modeling_qwen3.Qwen3Model'>


In [18]:
# Try importing the Lorentz model and do a quick sanity check
from geoopt.manifolds import Lorentz
import torch

k = 1.0

# Note that k is the negative curvature per the docs
hyperboloid = Lorentz(k=k)

u = torch.tensor([[1., 0., 0., 0.], [0., 1., 0., 0.]])
z = torch.zeros(size=(u.shape[0], 1))

u = torch.cat((z, u), dim=1)

p = torch.zeros(size=u.shape)
p[:, 0] = 1/(k ** 0.5)

print(u)
print(p)





# Exp_x(u)
u_hyp = hyperboloid.expmap(p, u)

print(u_hyp)

print(hyperboloid.k)

tensor([[0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.]])
tensor([[1., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0.]])
tensor([[1.5431, 1.1752, 0.0000, 0.0000, 0.0000],
        [1.5431, 0.0000, 1.1752, 0.0000, 0.0000]])
Parameter containing:
tensor(1.)
